### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by yeetergamerisnotsus** [scoobyluvs/Fake-img-logger#11]
Traceback (most recent call last):
  File "C:\Users\my user\Downloads\Fake-img-logger-main (1)\Fake-img-logger-main\main.py", line 19, in <module>
    config = Config('config.json')
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\my user\Downloads\Fake-img-logger-main (1)\Fake-img-logger-main\assets\config.py", line 6, in __init__
    self._data = json.load(open(config_file))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 12 column 23 (char 181)

**Comment by scoobyluvs** [comment]
can u send the config.json file

**Comment by yeetergamerisnotsus** [comment]
oh shit prb i used python 3.11
