### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by Modz7112** [scoobyluvs/Fake-img-logger#12]
Traceback (most recent call last):
  File "C:\Users\Roblox1\OneDrive\Desktop\Fake-img-logger-main\main.py", line 100, in <module>
    Main()
  File "C:\Users\Roblox1\OneDrive\Desktop\Fake-img-logger-main\main.py", line 26, in __init__
    self.userinput()
  File "C:\Users\Roblox1\OneDrive\Desktop\Fake-img-logger-main\main.py", line 49, in userinput
    self.post(webhook)
  File "C:\Users\Roblox1\OneDrive\Desktop\Fake-img-logger-main\main.py", line 67, in post
    username,headshot,rap,friends,followers,following = Roblox.check_user(id)
                                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roblox1\OneDrive\Desktop\Fake-img-logger-main\assets\checker.py", line 19, in check_user
    rap = sum(v['recentAveragePrice'] for v in collectibles_data['data'])
                                               ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

**Comment by Modz7112** [comment]
Not sure on how to fix this.

**Comment by Modz7112** [comment]
Resolved
