### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by w00io** [scoobyluvs/Fake-img-logger#8]
Traceback (most recent call last):
  File "C:\Fake-img-logger-main\main.py", line 100, in <module>
    Main()
  File "C:\Fake-img-logger-main\main.py", line 26, in __init__
    self.userinput()
  File "C:\Fake-img-logger-main\main.py", line 42, in userinput
    self.print015(f'{Fore.RED}[{config.program}]{Fore.WHITE} Welcome to {config.program} image logger !')
                     ^^^^
NameError: name 'Fore' is not defined

**Comment by scoobyluvs** [comment]
`pip install colorama` 

OR 

your path is fucked

**Comment by yeetergamerisnotsus** [comment]
> pip install coloram

but what should i do if my path is fucked
